DrOffice/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace DrOffice.Models
{
  public class DrOfficeContextFactory : IDesignTimeDbContextFactory<DrOfficeContext>
  {

    DrOfficeContext IDesignTimeDbContextFactory<DrOfficeContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<DrOfficeContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new DrOfficeContext(builder.Options);
    }
  }
}

DrOffice/Models/Doctor.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace DrOffice.Models
{
  public class Doctor
  {
    public Doctor()
    {
      this.Patients = new HashSet<DoctorPatient>();
    }

    public int DoctorId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }
    public virtual ICollection<DoctorPatient> Patients { get; set; }

  }
}

DrOffice/Models/DoctorPatient.cs
namespace DrOffice.Models
{
  public class DoctorPatient 
  {
    public int DoctorPatientId { get; set; }
    public int PatientId { get; set; }
    public int DoctorId { get; set; }
    public Patient Patient { get; set; }
    public Doctor Doctor { get; set; }
  }
}

DrOffice/Models/DrOfficeContext.cs
using Microsoft.EntityFrameworkCore;

namespace DrOffice.Models
{
  public class DrOfficeContext : DbContext
  {
    public DbSet<Doctor> Doctors { get; set; }
    public DbSet<Patient> Patients { get; set; }
    public DbSet<DoctorPatient> DoctorPatient { get; set; }
    
    public DrOfficeContext(DbContextOptions options) : base(options) { }
  }
}

DrOffice/Models/Patient.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace DrOffice.Models
{
  public class Patient
  {
    public Patient()
    {
      this.Doctors = new HashSet<DoctorPatient>();
    }
    
    public int PatientId { get; set; }
    public string Name { get; set; }
    public ICollection<DoctorPatient> Doctors { get; }
  }
}

DrOffice/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc;
using DrOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DrOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DrOfficeContext _db;

    public DoctorsController(DrOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Doctor> model = _db.Doctors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
          .Include(doctor => doctor.Patients)
          .ThenInclude(join => join.Patient)
          .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    public ActionResult Edit(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctors => doctors.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctors => doctors.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

DrOffice/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using DrOffice.Models;
using System.Collections.Generic;

namespace DrOffice.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

DrOffice/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc;
using DrOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DrOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DrOfficeContext _db;

    public PatientsController(DrOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Patient> model = _db.Patients.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
          .Include(patient => patient.Doctors)
          .ThenInclude(join => join.Doctor)
          .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult Edit(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }

      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      _db.Patients.Remove(thisPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      var joinEntry = _db.DoctorPatient.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDoctor(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

DrOffice/Views/Doctors/Create.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Doctor

<h4>Add a new doctor</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add a new doctor" />
}

<p>@Html.ActionLink("Show all doctors", "Index")</p>

DrOffice/Views/Doctors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Doctor

<h2>Are you sure you want to delete this doctor?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Doctors", "Index")

DrOffice/Views/Doctors/Details.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Doctor;

<h2>Doctor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.Patients.Count == 0)
{
  <p>This doctor does not have any patients assigned</p>
}
else
{
  <h4>Patients this Doctor sees</h4>
  <ul>
    @foreach (var join in Model.Patients)
    {
      <li>@join.Patient.Name</li>
      <li>@join.Patient.PatientId</li>
    }
  </ul>
}

<p>@Html.ActionLink("Back to Doctors", "Index")</p>
<p>@Html.ActionLink("Edit Doctor", "Edit", new { id = Model.DoctorId })</p>
<p>@Html.ActionLink("Delete Doctor", "Delete", new { id = Model.DoctorId })</p>

DrOffice/Views/Doctors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Doctor

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.DoctorId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Doctors", "Index")</p>

DrOffice/Views/Doctors/Index.cshtml
@{
  Layout = "_Layout";
}

@using DrOffice.Models;
@model List<DrOffice.Models.Doctor>;

<h1>Doctors</h1>

@if (@Model.Count == 0)
{
  <h3>No Doctors have been added to this clinic.</h3>
}

@foreach (Doctor doctor in Model)
{
  <li>@Html.ActionLink($"{doctor.Name}", "Details", new { id = doctor.DoctorId })</li>
}

<p>@Html.ActionLink("Add a new Doctor", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DrOffice/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Doctor's Office!</h1>

<p>@Html.ActionLink("View all Patients", "Index", "Patients")</p>
<p>@Html.ActionLink("View all Doctors", "Index", "Doctors")</p>

DrOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Patient

<h2>Add a doctor</h2>

<h4>Add a doctor for this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Assign!" />
}

<p>@Html.ActionLink("Back to List", "Index")</p>

DrOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Patient

<h4>Add a new Patient</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add a new patient" />
}

<p>@Html.ActionLink("Show all patients", "Index")</p>

DrOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Patient

<h2>Are you sure you want to delete this Patient?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Patients", "Index")

DrOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Patient

<h2>Patient Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.Doctors.Count == 0)
{
  <p>This patient does not have a primary doctor assigned.</p>
}
else
{
  <h4>Doctors that see this Patient:</h4>
}
<ul>
  @foreach(var join in Model.Doctors)
  {
    <li>@join.Doctor.Name</li>
    @using (Html.BeginForm("DeleteDoctor", "Patients"))
    {
      @Html.Hidden("joinId", @join.DoctorPatientId)
      <input type="submit" value="Delete"/>
    }
  }
</ul>

<p>@Html.ActionLink("Back to patient", "Index")</p>
<p>@Html.ActionLink("Edit Patient", "Edit", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Delete Patient", "Delete", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Add a Doctor", "AddDoctor", new { id = Model.PatientId })</p>

DrOffice/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DrOffice.Models.Patient

<h2>Edit Patient File</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)
  
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Select doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Patient", "Index")</p>

DrOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DrOffice.Models;
@model List<DrOffice.Models.Patient>;

<h1>Patients of this Clinic:</h1>

@if (@Model.Count == 0)
{
  <h3>No Patients have been added to this Clinic yet.</h3>
}

@foreach (Patient patient in Model)
{
  <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId })</li>
}

<p>@Html.ActionLink("Add a new Patient", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DrOffice/Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Doctor's Office Page</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>